apiVersion: apps/v1
kind: Deployment
metadata:
  name: live-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: live-server
  template:
    metadata:
      labels:
        app: live-server
    spec:
      containers:
        - name: live-server
          image: christer10/live_server:1.0.4
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: live-server-secrets
